### ISSUE TITLE
Invalid response from WebDriver when using hub/node vs standalone

### ISSUE THREAD

**Issue by xMutaGenx** [facebook/php-webdriver#525]
### What are you trying to achieve? (Expected behavior)

Able to create a firefox browser session and run the tests on a hub/node configuration

### What do you get instead? (Actual behavior)

When using the hub/node configuration, the response from the WebDriver is invalid and is breaking the session creation

### How could the issue be reproduced? (Steps to reproduce)
Launch:
hub: `java -jar selenium-server-standalone-3.8.1.jar -role hub -enablePassThrough false`
node: `java -jar selenium-server-standalone-3.8.1.jar -port 5556 -role node -hub http://localhost:4444/grid/register -browser "browserName=firefox"`

Execute the provided example test: `php -f example.php`

Standalone Response (correct)
```
object(Facebook\WebDriver\Remote\WebDriverResponse)#2 (3) {
  ["status":"Facebook\WebDriver\Remote\WebDriverResponse":private]=>
  int(0)
  ["value":"Facebook\WebDriver\Remote\WebDriverResponse":private]=>
  array(18) {
    ["moz:profile"]=>
    string(77) "/var/folders/27/hrq_gdl1005751zqnd71p7vw8y32x9/T/rust_mozprofile.XTha7JvNbvlG"
    ["rotatable"]=>
    bool(false)
    ["timeouts"]=>
    array(3) {
      ["implicit"]=>
      int(0)
      ["pageLoad"]=>
      int(300000)
      ["script"]=>
      int(30000)
    }
    ["pageLoadStrategy"]=>
    string(6) "normal"
    ["moz:headless"]=>
    bool(false)
    ["platform"]=>
    string(3) "MAC"
    ["moz:accessibilityChecks"]=>
    bool(false)
    ["webdriver.remote.sessionid"]=>
    string(36) "82c4e592-d892-4042-b8c7-505b64b708cd"
    ["acceptInsecureCerts"]=>
    bool(false)
    ["browserVersion"]=>
    string(4) "58.0"
    ["platformVersion"]=>
    string(6) "16.7.0"
    ["moz:processID"]=>
    int(10611)
    ["browserName"]=>
    string(7) "firefox"
    ["takesScreenshot"]=>
    bool(true)
    ["javascriptEnabled"]=>
    bool(true)
    ["platformName"]=>
    string(3) "MAC"
    ["cssSelectorsEnabled"]=>
    bool(true)
    ["moz:webdriverClick"]=>
    bool(true)
  }
  ["sessionID":"Facebook\WebDriver\Remote\WebDriverResponse":private]=>
  string(36) "82c4e592-d892-4042-b8c7-505b64b708cd"
}
```

Hub/Node Response (incorrect)
```
object(Facebook\WebDriver\Remote\WebDriverResponse)#2 (3) {
  ["status":"Facebook\WebDriver\Remote\WebDriverResponse":private]=>
  int(0)
  ["value":"Facebook\WebDriver\Remote\WebDriverResponse":private]=>
  array(2) {
    ["sessionId"]=>
    string(36) "fe7585d9-6f2e-4b0d-bee6-bfc499cfa65b"
    ["capabilities"]=>
    array(13) {
      ["moz:profile"]=>
      string(33) "/tmp/rust_mozprofile.YduYXeeEq9Rv"
      ["rotatable"]=>
      bool(false)
      ["timeouts"]=>
      array(3) {
        ["implicit"]=>
        int(0)
        ["pageLoad"]=>
        int(300000)
        ["script"]=>
        int(30000)
      }
      ["pageLoadStrategy"]=>
      string(6) "normal"
      ["moz:headless"]=>
      bool(false)
      ["moz:accessibilityChecks"]=>
      bool(false)
      ["acceptInsecureCerts"]=>
      bool(false)
      ["browserVersion"]=>
      string(4) "58.0"
      ["platformVersion"]=>
      string(20) "4.9.60-linuxkit-aufs"
      ["moz:processID"]=>
      int(76)
      ["browserName"]=>
      string(7) "firefox"
      ["platformName"]=>
      string(5) "linux"
      ["moz:webdriverClick"]=>
      bool(true)
    }
  }
  ["sessionID":"Facebook\WebDriver\Remote\WebDriverResponse":private]=>
  NULL
}
```

### Details

As you can see, the above responses differ and when we are trying to create a new driver session at https://github.com/facebook/php-webdriver/blob/community/lib/Remote/RemoteWebDriver.php#L129 we will always be passing a NULL

**Additionally**, it seems that a browser does not even get started when launching docker hub/node using docker with:

```
version : '3'
services:
    selenium-hub:
      image: selenium/hub:3.8.1-francium
      container_name: local-selenium-hub
      ports:
        - 4444:4444
      environment:
        - SE_OPTS=-enablePassThrough false
    firefox:
      image: selenium/node-firefox:3.8.1-francium
      environment:
        - HUB_PORT_4444_TCP_ADDR=local-selenium-hub
        - HUB_PORT_4444_TCP_PORT=4444
        - NODE_SELENIUM_PROTOCOL=WebDriver
      depends_on:
        - selenium-hub
```

* Php-webdriver version: community
* PHP version: 7.1.13
* Selenium server version: 3.8.1-francium
* Operating system: OSX
* Browser used + version: Firefox v58
