### ISSUE TITLE
Failing to launch firefox with MinkFacebookWebDriver

### ISSUE THREAD

**Issue by nirbhaypatil** [facebook/php-webdriver#597]
### What are you trying to achieve? (Expected behavior)

I am trying to use facebook/php-webdriver with Behat 3 
using silverstripe/MinkFacebookWebDriver [ https://github.com/silverstripe/MinkFacebookWebDriver]

and my  behat.yml is 
```
default:
  suites:
    default:
      paths:
        - %paths.base%/../features/
      contexts:
        - Behat\MinkExtension\Context\MinkContext
        - bootstrap\FeatureContext:
  extensions:
    bootstrap\MinkExtension:
      default_session: facebook_web_driver
      javascript_session: facebook_web_driver
      facebook_web_driver:
        wd_host: "http://localhost:4444/wd/hub" 
        capabilities: { 'firefox': {'profile':'/path to firefox profile/zkhe1wc2.behatfirefox.zip'} }
      base_url: 'http://www.url-to-open.com'
```
and composer.json is 
```
{
  "require": {
    "behat/behat": "~3.1",
    "facebook/webdriver": "1.4",
    "silverstripe/mink-facebook-web-driver": "1.0.0",
    "behat/mink-extension": "2.3.1"
  },
  "config": {
    "bin-dir": "bin/"
  },
  "autoload":{
  "psr-4":{
    "bootstrap\\": "features/bootstrap/",
    "SilverStripe\\BehatExtension\\": "features/bootstrap/"
  }
  }
}
```
### What do you get instead? (Actual behavior)

Getting below error instead of firefox session created .

 Could not open connection: Warning: ZipArchive::close(): Renaming temporary file failed: Invalid argument in /cygdrive/d/behat-facebook/vendor/facebook/webdriver/lib/Firefox/FirefoxProfile.php line 185 (Behat\Mink\Exception\DriverException)

### How could the issue be reproduced? (Steps to reproduce)

I have followed steps mentioned in readme doc here.
https://github.com/silverstripe/MinkFacebookWebDriver
and default browser is kept as firefox.

### Details

* Php-webdriver version: 1.4
* PHP version: 5.6.1
* Selenium server version: 3.5.0
* Operating system: Windows 7
* Browser used + version: Firefox 60.0 (64-bit)
