### ISSUE TITLE
WebDriverCurlException

### ISSUE THREAD

**Issue by jconroy** [facebook/php-webdriver#600]
### What are you trying to achieve? (Expected behavior)

We're running a batch of e2e tests/test flows - each test/test flow runs one after the other. Each test flow should consistently run one after the other. This usually happens.

### What do you get instead? (Actual behavior)

However we inevitably see weird behavior randomly and we get `WebDriverCurlException` every now an again with `Curl error thrown for http POST to /session/693db79xxxxxx/url with params {xxxx} Operation timed out after 687 milliseconds with 0 bytes received`

It affects different tests flows at different spots and after the error occurs the next test typically works fine - so its not a case of everything suddenly crashing (we don't do anything to resolve things and get the next test working).

Important to note the timeout is suuuper short and never consistent. For example the above is 687 ms, sometimes it will be around 360ms, other 548ms etc.

Does anyone have any ideas what could be causing this? I would be in your debt and greatly appreciate any pointers

---

We previously encountered issues similar to https://github.com/facebook/php-webdriver/issues/598 but we seem to have resolved them by ensuring we

* Increase the WebDriver connection and request timeouts to 60 seconds (we have a few test flows that can take a little time i..e more than 30 seconds due to to transactional processes taking a little time).
* making sure we always close drivers after any exceptions.

### Details

* Php-webdriver version: 1.3.0
* PHP version: 7.0

We use the selenium docker containers -> https://github.com/SeleniumHQ/docker-selenium/tree/3.14.0-arsenic

**Comment by jeremy379** [comment]
Hi
I got the same issue, my option was to fork the project and edit the execute() method in php-webdriver/lib/Remote/HttpCommandExecutor.php

Just after the method declaration I added 
`set_time_limit(0);`

And then a bit below after`curl_setopt($this->curl, CURLOPT_URL, $this->url . $url);`
I added 
`curl_setopt($this->curl, CURLOPT_CONNECTTIMEOUT, 0);`
`curl_setopt($this->curl, CURLOPT_TIMEOUT, 400); //timeout in seconds`

**Comment by jconroy** [comment]
Hi @jeremy379 thanks so much.

Ahhh interesting, I was under the impression the curl options were already being set e.g. https://github.com/facebook/php-webdriver/blob/community/lib/Remote/HttpCommandExecutor.php#L178-L179

I'll double check `set_time_limit()`

> Important to note the timeout is suuuper short and never consistent. For example the above is 687 ms, sometimes it will be around 360ms, other 548ms etc.

So you were seeing this sort of inconsistent timeouts before applying the above?

**Comment by OndraM** [comment]
Could you please provide:
- code you use to initialize RemoteWebDriver
- how exactly you start selenium container

You can try passing zero as a $connection_timeout_in_ms and $request_timeout_in_ms to see if there is any difference.

Something like:
```
$driver = RemoteWebDriver::create('http://localhost:4444/wd/hub', DesiredCapabilities::chrome(), 0, 0);
```

**Comment by OndraM** [comment]
@jeremy379 BTW no need to fork the project to be able to set the timeouts; you can pass desired timeout to the `create()` method of `RemoteWebDriver` - see above.

Also note `set_time_limit()`  is just about PHP script execution time, it is not related to CURL request timeout.

**Comment by jconroy** [comment]
👋 hey @OndraM thanks for the reply and thiinking

> code you use to initialize RemoteWebDriver

If I understand what you are after correctly It is basically

```
$capabilities = DesiredCapabilities::chrome();
$capabilities->setCapability( 'acceptSslCerts', true );
$driver = RemoteWebDriver::create( X.X.X.X, $capabilities, 60000, 60000 );
$window = new WebDriverDimension( 1600, 1005 );
$driver->manage()->window()->setSize( $window );
```

> how exactly you start selenium container

```
version: '3'
networks:
  private:
    driver: overlay
    ipam:
      config:
        - subnet: X.X.X.X/24
services:
  hub:
    image: selenium/hub:3.14.0-arsenic
    entrypoint: bash -c '/opt/bin/entry_point.sh'
    ports:
      - "4444:4444"
    deploy:
     replicas: 1
     placement:
       constraints:
         - node.role == worker
    networks:
     - private
  chrome:
    image: selenium/node-chrome:3.14.0-arsenic
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444
      - NODE_MAX_SESSION=1
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1080
    entrypoint: bash -c 'SE_OPTS="-host $$HOSTNAME -port 5555" /opt/bin/entry_point.sh'
    ports:
      - "5555:5555"
    deploy:
      replicas: 4
    networks:
- private
```

> You can try passing zero as a $connection_timeout_in_ms and $request_timeout_in_ms to see if there is any difference.

I don't think we have the resources/setup to allow things to run indefinitely, but I'll keep it in mind.
