### ISSUE TITLE
Chrome ignores all the arguments and extensions from php-webdriver

### ISSUE THREAD

**Issue by commanddotcom** [facebook/php-webdriver#649]
### What are you trying to achieve? (Expected behavior)
I'm trying to add arguments with `addArguments()` method and to add extensions with `addExtensions()` method. 

### What do you get instead? (Actual behavior)
Values in `addExtensions()` and `addExtensions()` doesn't have impact on outcome which I can see on the page `chrome://version/`

### How could the issue be reproduced? (Steps to reproduce)
I'm using SeleniumHQ/docker-selenium to run Selenium. So `docker-compose.yaml` is like:

```
...
    selenium-hub:
        container_name: selenium-hub
        image: selenium/hub:latest
        ports:
            - "4444:4444"
    chrome:
        container_name: chrome
        image: selenium/node-chrome:latest
        volumes:
            - /dev/shm:/dev/shm
        depends_on:
            - selenium-hub
        environment:
           - HUB_HOST=selenium-hub
           - HUB_PORT=4444
           - SCREEN_WIDTH=1280 
           - SCREEN_HEIGHT=800
           - SCREEN_DEPTH=24
        entrypoint: bash -c 'SE_OPTS="-host $$HOSTNAME" /opt/bin/entry_point.sh'
...
```
PHP code:

```php
        $options = (new ChromeOptions())
            ->addArguments([
            '--window-size=640x480',
            ]);
        $capabilities = DesiredCapabilities::chrome();
        $capabilities->setCapability(ChromeOptions::CAPABILITY, $options);
        $driver = RemoteWebDriver::create('http://selenium-hub:4444/wd/hub/', $capabilities, 5000);
        $driver->get('chrome://version/');
        header("Content-Type: image/jpeg");
        echo $driver->takeScreenshot();
        $driver->quit();
```

For some reason params in addArguments() doesn't have any impact - the outcome is always the same no matter what was set in the method addArguments(). It is always something like [this](https://i.stack.imgur.com/V6eMA.png). I tried adding `--disable-gpu`, `--start-maximized` and other params but _Command Line_ was the same.

### Details

* Php-webdriver version: 1.7.1
* PHP version: 7.2.19
* Selenium server version: 3.141.59
* Operating system: Alpine Linux
* Browser used + version: Chrome 75.0.3770.90
* SeleniumHQ/docker-selenium: 3.141.59

**Comment by commanddotcom** [comment]
The issue was related to docker. I don't know what was wrong with original version of `docker-compose.yaml` using chrome node, but standalone-chrome works:

```
 selenium-hub:
        container_name: selenium-hub
        image: selenium/standalone-chrome
        volumes:
            - /dev/shm:/dev/shm
        ports:
            - "4444:4444"
        environment:
           - HUB_HOST=selenium-hub
           - HUB_PORT=4444
           - SCREEN_WIDTH=1280 
           - SCREEN_HEIGHT=800
           - SCREEN_DEPTH=24
```
